apiVersion: apps/v1
kind: Deployment
metadata:
  name: wb01-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wb01
  template:
    metadata:
      labels:
        app: wb01
    spec:
      containers:
      - name: wb01
        image: jnims07/wb01:latest  
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: wb01-service
spec:
  type: NodePort
  selector:
    app: wb01
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 36001
