name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Change to your default branch

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update version
        run: |
          powershell -ExecutionPolicy Bypass -File .\update_version.ps1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: jnims07/demo1cicd:latest

      - name: Set up Kubernetes
        uses: imranismail/setup-kubectl@v1
        with:
          kubectl-version: 'latest' # Specify the version of kubectl you want to use

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f path\to\your\deployment.yaml
          kubectl set image deployment/testcicd-deployment-1 testcicd-container-1=jnims07/demo1cicd:latest
